Dovid/Controllers/AddController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dovid.Models;
using Dovid.Filters;

namespace Dovid.Controllers
{
    [Culture]
    public class AddController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        [Authorize(Roles = "admin")]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Train train)
        {
            if(!ModelState.IsValid)
            { 
                Response.Write("<script>window.alert('Заповніть всі поля!');</script>");
                return View();
            }
            else
            {
                db.Trains.Add(train);
                db.SaveChanges();
                return RedirectToAction("../home/");
            }
        }
    }
}

Dovid/Controllers/StationController.cs
using Dovid.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dovid.Filters;
namespace Dovid.Controllers
{
    [Culture]
    public class StationController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            IEnumerable<Station> stations = db.Stations;

            ViewBag.Stations = stations;
            return View();
        }
        [Authorize(Roles = "admin")]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Station station)
        {
            if (!ModelState.IsValid)
            {
                Response.Write("<script>window.alert('Заповніть всі поля!');</script>");
                return View();
            }
            else
            {
                db.Stations.Add(station);
                db.SaveChanges();
                return RedirectToAction("../home/");
            }
        }
        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Station station = db.Stations.Find(id);
            ViewBag.Trains = db.Trains.ToList();
            if (station != null)
            {
                return View(station);
            }
            return HttpNotFound();
        }
        [HttpPost]
        public ActionResult Edit(Station station, int[] selectedTrains)
        {
            Station newStation = db.Stations.Find(station.Id);
            newStation.Name = station.Name;
            newStation.Oblast = station.Oblast;
            newStation.Trains.Clear();
            if (selectedTrains != null)
            {
                foreach (var t in db.Trains.Where(co =>
               selectedTrains.Contains(co.Id)))
                {
                    newStation.Trains.Add(t);
                }
            }
            db.Entry(newStation).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Station b = db.Stations.Find(id);
            if (b == null)
            {
                return HttpNotFound();
            }
            return View(b);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Station s = db.Stations.Find(id);
            if (s == null)
            {
                return HttpNotFound();
            }
            db.Stations.Remove(s);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Dovid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Resources.Resource.Dovid, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Resources.Resource.Showstation, "Index", "Station")</li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink(Resources.Resource.Addtrain, "Add", "Add")</li>
                        <li>@Html.ActionLink(Resources.Resource.Addstation, "Add", "Station")</li>
                    }
                    <li>@Html.Partial("_LoginPartial")</li>
                </ul>
                <div>
                    @using (Html.BeginForm("ChangeCulture", "Home"))
                    {
                        <select name="lang">
                            <option disabled selected>@Resources.Resource.ChooseLang</option>
                            <option value="uk">Українська</option>
                            <option value="en">English</option>
                        </select>
                        <input type="submit" name="submit" value="@Resources.Resource.ChooseLang">
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>